apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: docker-registry
  namespace: kube-system
spec:
  chart:
    repository: https://helm.twun.io
    name: docker-registry
    version: 1.10.1
  releaseName: docker-registry
  values:
    persistence:
      enabled: true
      storageClass: "local"
      size: 1Gi
